### ISSUE TITLE
[Feature Request] Add option to only save wins or losses

### ISSUE THREAD

**Issue by Al12rs** [ubelhj/AutoSavePrivateReplay#1]
I would like to be able to only save the matches where I lost so that I can analyze them later for mistakes and self improvement.
I also imagine other people might want to instead selectively save their wins to keep their highlights.

Do you think this is something you would be interested in adding in the plugin?

**Comment by ubelhj** [comment]
If possible, this wouldn't be that hard. I'll do some testing in the next couple days and see if it is. My hunch though is that BakkesMod saves the replay the same instant that you know which team won the game, which would make it not work.

**Comment by ubelhj** [comment]
Gave it a shot, and as expected it didn't work. My plugin knows who won too late to tell BakkesMod to save the replay.

**Comment by Al12rs** [comment]
I understand, thank you very much for trying it, I appreciate it!
